### ISSUE TITLE
feat(mafia): Content from BOTC's Trouble Brewing

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1600]
Acceptance Criteria:
- Selectively develop roles and mechanics inspired by each of Blood on the Clocktower's official scripts, starting with Trouble Brewing
- Content will have to be tweaked to fit the format of Mafia; this may constitute a larger issue/project
- lots of roles and mechanics will be renamed
- https://wiki.bloodontheclocktower.com/Trouble_Brewing

pinging @SawJester

**Comment by SawJester** [comment]
Currently Making Investigator and Washerwomen

**Comment by SawJester** [comment]
Current Progress
- [ ]  Washerwomen - Added as Inspector
- [ ] Investigator - Added
- [ ] Librarian - Requires the Outsider mechanic to be added.
- [ ] Chef
- [ ] Empath - Added
- [ ] Fortune Teller - Kind of added as Justice
- [ ] Undertaker - Kind of added as Coroner
- [ ] Monk - added as Doctor
- [ ] Ravenkeeper - Kind of added as Oracle
- [ ] Virgin
- [ ] Slayer
- [ ] Soldier - Kind of Added as Commutor/ Villager (Bulletproofx3)
- [ ] Mayor
- [ ] Butler
- [ ] Saint
- [ ] Recluse - Added as Miller
- [ ] Drunk - Requires Droison be added
- [ ] Poisoner - Requires Droison (But Kind of added as Hooker/Succubus)
- [ ] Baron - Requires Outsider mechanic
- [ ] Scarlet Woman
- [ ] Imp

**Comment by Golbolco** [comment]
User feedback on Analyst: too many actions, can be streamlined

- One option is to use a multi action (compare to Justice or Baker) with a max input of 5. Select 5 players and 5 roles in two separate actions
- Another option: Have the game give an array of 5 roles and then the Analyst picks 5 players as their guess; less freedom with this option

Another point of feedback is that Analyst could scale the bigger or smaller a game is. 5 guesses max, but only 2 or 3 for 7-9 player games. Scaling a role seems like it would take extensive code redesign, but if done correctly could also be backwards applied to roles like Baker
