### ISSUE TITLE
feat(mafia): Content from BOTC's Sects and Violets

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1601]
Acceptance Criteria:
- Selectively develop roles and mechanics inspired by each of Blood on the Clocktower's official scripts, including Sects and Violets
- Content will have to be tweaked to fit the format of Mafia; this may constitute a larger issue/project
- lots of roles and mechanics will be renamed
- https://wiki.bloodontheclocktower.com/Sects_%26_Violets

pinging @SawJester

**Comment by SawJester** [comment]
- [ ] Clockmaker
- [ ] Dreamer
- [ ] Snake Charmer
- [ ] Mathematician
- [ ] Flowergirl
- [ ] Town Crier (Will likely be the same role as Flowergirl )
- [ ] Oracle
- [ ] Savant
- [ ] Seamstress -added as Justice (One shot)
- [ ] Philosopher
- [ ] Artist- Basically Impossible to add.
- [ ] Juggler- added as Analyst
- [ ] Sage- 
- [ ] Mutant- Basically Impossible to add 
- [ ] Sweetheart- Requires Droision
- [ ] Barber
- [ ] Klutz
- [ ] Evil Twin
- [ ] Witch- added as Diabolist
- [ ] Cerenovous- kind of added as Jinx
- [ ] Pit Hag
- [ ] Fang Gu- Requires Outsiders be added
- [ ] Vigormortis
- [ ] No Dashi- Requires  Droision
- [ ] Vortox- Requires re-coding every Investigative role to have a false mode.

**Comment by SawJester** [comment]
Currently Making Fang Gu

**Comment by Golbolco** [comment]
Possible Snake Charmer bug: https://ultimafia.com/game/4lIxZrWYy/review Converted to Slayer

Feedback for Princess: Effect could be like an inverted Frustrated modifier effect. When voted by a village-aligned player, the day goes on as usual but will always resolve with the death of the first village-aligned voter
