### ISSUE TITLE
feat(mafia): Content from BOTC's Bad Moon Rising

### ISSUE THREAD

**Issue by Golbolco** [UltiMafia/Ultimafia#1602]
Acceptance Criteria:
- Selectively develop roles and mechanics inspired by each of Blood on the Clocktower's official scripts, including Bad Moon Rising
- Content will have to be tweaked to fit the format of Mafia; this may constitute a larger issue/project
- lots of roles and mechanics will be renamed
- https://wiki.bloodontheclocktower.com/Bad_Moon_Rising

pinging @SawJester

**Comment by SawJester** [comment]
- [ ] Grandmother
- [ ] Sailor - Requires Droision
- [ ] Chambermaid
- [ ] Exorcist - added as Drunk (DisLoyal)
- [ ] Innkeeper
- [ ] Gambler
- [ ] Gossip
- [ ] Courtier
- [ ] Professor - Added as Ressurrectionist 
- [ ] Minstrel - Requires Droision
- [ ] Tea Lady - Added
- [ ] Pacifist
- [ ] Fool
- [ ] Goon
- [ ] Lunatic - Basically impossible to add.
- [ ] Tinker
- [ ] Moon-child
- [ ]  Godfather - Requires Outsiders
- [ ] Devil's Advocate
- [ ] Assassin - Added as Hitman (One Shot)
- [ ] Mastermind 
- [ ] Zombuul
- [ ] Pukka - Requires Droision
- [ ] Shabaloth
- [ ] Po

**Comment by Golbolco** [comment]
Just a couple notes:
- Grandmother: could be a modifier. Possibly just called "Married"
- Sailor: also has modifier potential (50% chance your action will be redirected onto yourself)
- Gossip: This feels impossible to me? Not sure
- Courtier: this is kind of like a town-sided lobotomist, basically accomplished by Mime
- Mastermind: Also feels impossible, but if I can be proven wrong that would be great

**Comment by SawJester** [comment]
Currently Making Inn Keeper
